apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  labels:
    app: n8n
    component: secrets
stringData:
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_PASSWORD: "n8n"
  DB_POSTGRESDB_HOST: "n8n-postgres.default.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"
  # Basic auth credentials
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "n8n"
  N8N_BASIC_AUTH_PASSWORD: "n8n"
  N8N_PROTOCOL: "http"
  N8N_PORT: "5678"

#  N8N_HOST: "your.domain.com"
#  N8N_ENCRYPTION_KEY: "{{ PASSWORD }}"
#  GENERIC_TIMEZONE: "Europe/Lisbon"
#  WEBHOOK_TUNNEL_URL: "https://your.domain.com/"
  NODE_ENV: "production"
  N8N_METRICS: "true"
  # Increase node max memory
  NODE_OPTIONS: "--max_old_space_size=1024"
  # Set n8n to work as single thread instead of forking to worker threads
  EXECUTIONS_PROCESS: "main"
